export enum GamePlayState {
	IDLE = 'IDLE',
	PLAYING = 'PLAYING',
	CHECK_SOLUTION = 'CHECK_SOLUTION',
	ACCEPT_ANSWER = 'ACCEPT_ANSWER',
	WRONG_TRIAD = 'WRONG_TRIAD',
	CORRECT_ANSWER = 'CORRECT_ANSWER',
	WRONG_ANSWER = 'WRONG_ANSWER',
	WON = 'WON',
	LOST = 'LOST',
}
